apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  spring.datasource.username: root
  V1__initial_db.sql: |    
    DROP DATABASE pages IF EXISTS;
    CREATE DATABASE pages;
  V2__inital_schema.sql: |
    USE pages;
    create table pages(
    id bigint(20) not null auto_increment,
    business_name VARCHAR(50),
    address VARCHAR(50),
    category_id bigint(20),
    contact_number VARCHAR(50),
    primary key (id)
    )
    engine = innodb
    default charset = utf8;